language: java
jdk:
    - oraclejdk8

sudo: required

before_install:
    - sudo apt-get install build-essential
    - export COMPILER=g++-4.8
    - export COMP=gcc

before_script:
    - cd ./stockfish-6-src/src/
    - make build ARCH=x86-64
    - cd ../../../
