language: java
jdk:
    - oraclejdk8

sudo: required

before_install:
    - sudo apt-get install build-essential

before_script:
    - cd ./stockfish-6-src/src/
    - make build ARCH=x86-64
    - cd ../../../
